apiVersion: v1
kind: Service
metadata:
  name: mysql-spring
  labels: mysql-spring
spec:
  ports:
  - port: 3306
  selector:
    app: mysql-spring
    tier: mysql
  clusterIP: None

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-spring
spec:
  selector:
    matchLabels:
      app: mysql-spring
      tier: "mysql"
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-spring
        tier: "mysql"
    spec:
      containers:
      - image: mysql:8.0
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: pv-nfs-mysqldata
