apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-mysqldata
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.56.101
    path: /export/mysql/data
